spring.application.name=Webshop
spring.datasource.url=jdbc:postgresql://localhost:5432/webshop
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.profiles.active=dev
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = create-drop
server.port=8080